version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres # Database name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_SSLMODE: disable
    ports:
      - "8080:8080"
    # Wait for db to be ready before starting (optional)
    command: sh -c "sleep 5 && ./server"

volumes:
  pgdata: